"""NAI vs Animagine 비교용 공통 잡 데이터 100건"""

STYLE_PRESETS = [
    "pale_aqua", "mono_halftone", "chibi_sketch", "cozy_gouache",
    "watercolor_sketch", "kyoto_animation", "ufotable", "shinkai",
    "ghibli", "trigger", "mappa", "shaft", "monogatari",
    "genshin", "blue_archive", "arknights", "fate", "cyberpunk",
    "pastel_soft", "inuyasha", "sepia_backlit", "mono_accent",
    "sketch_colorpop", "pop_fanart", "split_sketch", "waterful",
    "retro_glitch",
]

JOBS: list[dict] = [
    # === 모노가타리 캐릭터 (27장 - 프리셋 1:1 매칭) ===
    {"prompt": "1girl, senjougahara hitagi, monogatari, long purple hair, sharp eyes, head tilt, looking at viewer, upper body", "style": "monogatari", "name": "hitagi_monogatari"},
    {"prompt": "1girl, hanekawa tsubasa, monogatari, black hair, braids, glasses, gentle smile, upper body", "style": "pale_aqua", "name": "hanekawa_pale_aqua"},
    {"prompt": "1girl, black hanekawa, monogatari, white hair, cat ears, golden eyes, seductive, upper body", "style": "mono_halftone", "name": "black_hanekawa_mono"},
    {"prompt": "1girl, oshino shinobu, monogatari, blonde hair, golden eyes, vampire, sitting, crossed legs", "style": "cyberpunk", "name": "shinobu_cyberpunk"},
    {"prompt": "1girl, sengoku nadeko, monogatari, orange hair, bangs, shy, cute, upper body", "style": "pastel_soft", "name": "nadeko_pastel"},
    {"prompt": "1girl, kanbaru suruga, monogatari, short dark hair, athletic, tomboy, dynamic pose", "style": "trigger", "name": "kanbaru_trigger"},
    {"prompt": "1girl, hachikuji mayoi, monogatari, twintails, backpack, cheerful, full body", "style": "chibi_sketch", "name": "hachikuji_chibi"},
    {"prompt": "1girl, araragi karen, monogatari, long black hair, ponytail, tall, confident, full body", "style": "ufotable", "name": "karen_ufotable"},
    {"prompt": "1girl, araragi tsukihi, monogatari, short black hair, kimono, cute, upper body", "style": "inuyasha", "name": "tsukihi_inuyasha"},
    {"prompt": "1girl, oikura sodachi, monogatari, light brown hair, twintails, sharp eyes, intense", "style": "mappa", "name": "sodachi_mappa"},
    {"prompt": "1girl, oshino ougi, monogatari, short black hair, mysterious, dark outfit, enigmatic", "style": "shaft", "name": "ougi_shaft"},
    {"prompt": "1girl, ononoki yotsugi, monogatari, green hair, hat, expressionless, full body", "style": "pop_fanart", "name": "yotsugi_pop"},
    {"prompt": "1boy, araragi koyomi, monogatari, black hair, ahoge, school uniform, looking at viewer", "style": "sketch_colorpop", "name": "araragi_sketch"},
    {"prompt": "1girl, senjougahara hitagi, monogatari, long purple hair, elegant, side profile", "style": "watercolor_sketch", "name": "hitagi_watercolor"},
    {"prompt": "1girl, hanekawa tsubasa, monogatari, black hair, glasses, reading, focused", "style": "kyoto_animation", "name": "hanekawa_kyoani"},
    {"prompt": "1girl, oshino shinobu, monogatari, blonde hair, donut, cheerful, cute", "style": "ghibli", "name": "shinobu_ghibli"},
    {"prompt": "1girl, kanbaru suruga, monogatari, short hair, basketball, energetic", "style": "blue_archive", "name": "kanbaru_blue_archive"},
    {"prompt": "1girl, senjougahara hitagi, monogatari, school uniform, stapler, confident smirk", "style": "mono_accent", "name": "hitagi_mono_accent"},
    {"prompt": "1girl, sengoku nadeko, monogatari, orange hair, snake motif, mysterious", "style": "fate", "name": "nadeko_fate"},
    {"prompt": "1girl, black hanekawa, monogatari, white hair, cat ears, night, moonlight", "style": "sepia_backlit", "name": "black_hanekawa_sepia"},
    {"prompt": "1girl, araragi karen, monogatari, ponytail, martial arts pose, dynamic", "style": "arknights", "name": "karen_arknights"},
    {"prompt": "1girl, araragi tsukihi, monogatari, kimono, cherry blossoms, peaceful", "style": "waterful", "name": "tsukihi_waterful"},
    {"prompt": "1girl, oshino ougi, monogatari, mysterious smile, dark, close up face", "style": "retro_glitch", "name": "ougi_retro_glitch"},
    {"prompt": "1girl, hanekawa tsubasa, monogatari, braids, gentle, wind, hair flowing", "style": "shinkai", "name": "hanekawa_shinkai"},
    {"prompt": "1girl, senjougahara hitagi, monogatari, purple hair, dramatic, close up", "style": "split_sketch", "name": "hitagi_split"},
    {"prompt": "1girl, hachikuji mayoi, monogatari, twintails, ghost, ethereal, soft", "style": "cozy_gouache", "name": "hachikuji_cozy"},
    {"prompt": "1girl, ononoki yotsugi, monogatari, green hair, hat, fantasy outfit, magic", "style": "genshin", "name": "yotsugi_genshin"},

    # === 케이온 캐릭터 (15장) ===
    {"prompt": "1girl, hirasawa yui, k-on!, brown short hair, brown eyes, guitar, cheerful, upper body", "style": "kyoto_animation", "name": "yui_kyoani"},
    {"prompt": "1girl, akiyama mio, k-on!, black long hair, grey eyes, bass guitar, shy, upper body", "style": "pale_aqua", "name": "mio_pale_aqua"},
    {"prompt": "1girl, tainaka ritsu, k-on!, brown short hair, headband, energetic, drumsticks", "style": "trigger", "name": "ritsu_trigger"},
    {"prompt": "1girl, kotobuki tsumugi, k-on!, blonde long hair, blue eyes, elegant, tea", "style": "pastel_soft", "name": "mugi_pastel"},
    {"prompt": "1girl, nakano azusa, k-on!, black twintails, red eyes, guitar, serious", "style": "monogatari", "name": "azusa_monogatari"},
    {"prompt": "2girls, hirasawa yui, nakano azusa, k-on!, senpai kouhai, guitar, music room", "style": "pop_fanart", "name": "yui_azusa_pop"},
    {"prompt": "2girls, akiyama mio, tainaka ritsu, k-on!, childhood friends, playful, after school", "style": "watercolor_sketch", "name": "mio_ritsu_watercolor"},
    {"prompt": "5girls, hirasawa yui, akiyama mio, tainaka ritsu, kotobuki tsumugi, nakano azusa, k-on!, tea time, club room", "style": "ghibli", "name": "htt_tea_ghibli"},
    {"prompt": "1girl, hirasawa yui, k-on!, brown hair, sunset, nostalgic, looking at sky", "style": "shinkai", "name": "yui_shinkai"},
    {"prompt": "1girl, akiyama mio, k-on!, black hair, elegant, night, spotlight", "style": "cyberpunk", "name": "mio_cyberpunk"},
    {"prompt": "1girl, hirasawa yui, k-on!, cheerful, running, full body, energetic", "style": "chibi_sketch", "name": "yui_chibi"},
    {"prompt": "1girl, kotobuki tsumugi, k-on!, blonde hair, piano, graceful", "style": "fate", "name": "mugi_fate"},
    {"prompt": "1girl, nakano azusa, k-on!, twintails, cat ears, playful", "style": "mono_halftone", "name": "azusa_mono"},
    {"prompt": "5girls, k-on!, live concert, full band, dramatic spotlight, crowd", "style": "mappa", "name": "htt_live_mappa"},
    {"prompt": "1girl, akiyama mio, k-on!, black long hair, beach, summer, wind", "style": "waterful", "name": "mio_waterful"},

    # === 프리렌 캐릭터 (12장) ===
    {"prompt": "1girl, frieren, sousou no frieren, white hair, elf ears, staff, calm expression, upper body", "style": "pale_aqua", "name": "frieren_pale_aqua"},
    {"prompt": "1girl, fern, sousou no frieren, purple hair, twintails, magic, determined", "style": "ufotable", "name": "fern_ufotable"},
    {"prompt": "1boy, himmel, sousou no frieren, blue hair, hero, handsome, sword, noble", "style": "fate", "name": "himmel_fate"},
    {"prompt": "1girl, frieren, sousou no frieren, white hair, elf, reading, library, peaceful", "style": "kyoto_animation", "name": "frieren_kyoani"},
    {"prompt": "2girls, frieren, fern, sousou no frieren, master and student, magic practice, warm", "style": "cozy_gouache", "name": "frieren_fern_cozy"},
    {"prompt": "1girl, frieren, sousou no frieren, white hair, sunset, nostalgic, emotional", "style": "shinkai", "name": "frieren_shinkai"},
    {"prompt": "1girl, frieren, sousou no frieren, elf, flower field, peaceful, full body", "style": "ghibli", "name": "frieren_ghibli"},
    {"prompt": "1girl, fern, sousou no frieren, purple hair, confident, magic pose, dramatic", "style": "mappa", "name": "fern_mappa"},
    {"prompt": "1girl, frieren, sousou no frieren, white hair, ancient ruins, mysterious", "style": "arknights", "name": "frieren_arknights"},
    {"prompt": "1girl, frieren, sousou no frieren, white hair, close up face, gentle smile", "style": "split_sketch", "name": "frieren_split"},
    {"prompt": "1girl, frieren, sousou no frieren, elf, night sky, stargazing, melancholic", "style": "sepia_backlit", "name": "frieren_sepia"},
    {"prompt": "1girl, fern, sousou no frieren, purple hair, school uniform au, modern", "style": "blue_archive", "name": "fern_blue_archive"},

    # === 체인소맨 캐릭터 (10장) ===
    {"prompt": "1girl, power, chainsaw man, blonde hair, horns, sharp teeth, wild, crazy eyes", "style": "trigger", "name": "power_trigger"},
    {"prompt": "1girl, makima, chainsaw man, red hair, ringed eyes, calm, terrifying beauty", "style": "mono_accent", "name": "makima_mono_accent"},
    {"prompt": "1girl, reze, chainsaw man, dark hair, bob cut, gentle smile, bomb motif", "style": "retro_glitch", "name": "reze_retro_glitch"},
    {"prompt": "1girl, power, chainsaw man, blonde hair, horns, cat, playful, loud", "style": "chibi_sketch", "name": "power_chibi"},
    {"prompt": "1girl, makima, chainsaw man, red hair, business suit, office, cold", "style": "cyberpunk", "name": "makima_cyberpunk"},
    {"prompt": "1girl, reze, chainsaw man, dark hair, rain, night, lonely, melancholic", "style": "watercolor_sketch", "name": "reze_watercolor"},
    {"prompt": "1girl, asa mitaka, chainsaw man, black hair, school uniform, nervous, upper body", "style": "pop_fanart", "name": "asa_pop"},
    {"prompt": "1girl, power, chainsaw man, dramatic, action pose, blood, intense", "style": "ufotable", "name": "power_ufotable"},
    {"prompt": "1girl, makima, chainsaw man, mysterious smile, dogs, elegant", "style": "shaft", "name": "makima_shaft"},
    {"prompt": "1girl, reze, chainsaw man, casual clothes, cafe, warm, date", "style": "pastel_soft", "name": "reze_pastel"},

    # === 스파이패밀리 (6장) ===
    {"prompt": "1girl, anya forger, spy x family, pink hair, green eyes, cute, excited, heh", "style": "chibi_sketch", "name": "anya_chibi"},
    {"prompt": "1girl, yor forger, spy x family, long black hair, red eyes, elegant, deadly", "style": "fate", "name": "yor_fate"},
    {"prompt": "1girl, anya forger, spy x family, pink hair, school uniform, peanuts, happy", "style": "pop_fanart", "name": "anya_pop"},
    {"prompt": "1girl, yor forger, spy x family, black dress, assassin, moonlight, dramatic", "style": "mappa", "name": "yor_mappa"},
    {"prompt": "1girl, anya forger, spy x family, pink hair, penguin plush, sleepy, cute", "style": "pastel_soft", "name": "anya_pastel"},
    {"prompt": "2girls, yor forger, anya forger, spy x family, mother daughter, warm, shopping", "style": "kyoto_animation", "name": "yor_anya_kyoani"},

    # === 보치 더 록 (8장) ===
    {"prompt": "1girl, gotou hitori, bocchi the rock, pink hair, shy, guitar, nervous, upper body", "style": "pale_aqua", "name": "bocchi_pale_aqua"},
    {"prompt": "1girl, ijichi nijika, bocchi the rock, blonde hair, drummer, cheerful, energetic", "style": "blue_archive", "name": "nijika_blue_archive"},
    {"prompt": "1girl, yamada ryo, bocchi the rock, blue hair, cool, bass guitar, composed", "style": "mono_halftone", "name": "ryo_mono"},
    {"prompt": "1girl, kita ikuyo, bocchi the rock, red hair, guitar, sparkling, happy", "style": "genshin", "name": "kita_genshin"},
    {"prompt": "4girls, gotou hitori, ijichi nijika, yamada ryo, kita ikuyo, bocchi the rock, band, live stage", "style": "trigger", "name": "kessoku_band_trigger"},
    {"prompt": "1girl, gotou hitori, bocchi the rock, pink hair, closet, hiding, anxious, dark", "style": "sketch_colorpop", "name": "bocchi_sketch"},
    {"prompt": "1girl, gotou hitori, bocchi the rock, pink hair, guitar solo, spotlight, serious", "style": "monogatari", "name": "bocchi_monogatari"},
    {"prompt": "2girls, gotou hitori, kita ikuyo, bocchi the rock, guitar practice, close, warm", "style": "cozy_gouache", "name": "bocchi_kita_cozy"},

    # === 냥냥돌쇠 OC (10장) ===
    {"prompt": "1girl, cat ears, cat tail, dark blue hair, bob cut, amber eyes, gentle smile, upper body", "style": "pale_aqua", "name": "dolsoe_pale_aqua"},
    {"prompt": "1girl, cat ears, cat tail, dark blue hair, bob cut, amber eyes, mischievous smile, playful", "style": "monogatari", "name": "dolsoe_monogatari"},
    {"prompt": "1girl, cat ears, cat tail, dark blue hair, bob cut, amber eyes, cozy room, reading", "style": "kyoto_animation", "name": "dolsoe_kyoani"},
    {"prompt": "1girl, cat ears, cat tail, dark blue hair, bob cut, amber eyes, night city, neon", "style": "cyberpunk", "name": "dolsoe_cyberpunk"},
    {"prompt": "1girl, cat ears, cat tail, dark blue hair, bob cut, amber eyes, school uniform, rooftop", "style": "blue_archive", "name": "dolsoe_blue_archive"},
    {"prompt": "1girl, cat ears, cat tail, dark blue hair, bob cut, amber eyes, wind, cherry blossoms", "style": "shinkai", "name": "dolsoe_shinkai"},
    {"prompt": "1girl, cat ears, cat tail, dark blue hair, bob cut, amber eyes, dynamic pose, cool", "style": "trigger", "name": "dolsoe_trigger"},
    {"prompt": "1girl, cat ears, cat tail, dark blue hair, bob cut, amber eyes, close up face, head tilt", "style": "split_sketch", "name": "dolsoe_split"},
    {"prompt": "1girl, cat ears, cat tail, dark blue hair, bob cut, amber eyes, cat pose, paw hands, nya", "style": "pop_fanart", "name": "dolsoe_pop"},
    {"prompt": "1girl, cat ears, cat tail, dark blue hair, bob cut, amber eyes, sunset, emotional, wind", "style": "waterful", "name": "dolsoe_waterful"},

    # === 기타 인기 캐릭터 (12장) ===
    {"prompt": "1girl, violet evergarden, prosthetic hands, military uniform, elegant, flowers, emotional", "style": "kyoto_animation", "name": "violet_kyoani"},
    {"prompt": "1girl, rem, re:zero, blue hair, maid outfit, gentle, devoted", "style": "pale_aqua", "name": "rem_pale_aqua"},
    {"prompt": "1girl, megumin, konosuba, brown hair, witch hat, explosion magic, excited", "style": "trigger", "name": "megumin_trigger"},
    {"prompt": "1girl, asuka langley, evangelion, red hair, plugsuit, tsundere, confident", "style": "retro_glitch", "name": "asuka_retro"},
    {"prompt": "1girl, rei ayanami, evangelion, blue hair, short hair, calm, bandages, mysterious", "style": "mono_accent", "name": "rei_mono_accent"},
    {"prompt": "1girl, zero two, darling in the franxx, pink hair, horns, playful, lollipop", "style": "sketch_colorpop", "name": "zerotwo_sketch"},
    {"prompt": "1girl, chika fujiwara, kaguya-sama, silver hair, ribbon, cheerful, love detective", "style": "pop_fanart", "name": "chika_pop"},
    {"prompt": "1girl, kaguya shinomiya, kaguya-sama, black hair, ribbon, ojou-sama, elegant", "style": "shaft", "name": "kaguya_shaft"},
    {"prompt": "1girl, nezuko kamado, demon slayer, bamboo mouthpiece, pink eyes, cute", "style": "ghibli", "name": "nezuko_ghibli"},
    {"prompt": "1girl, nico robin, one piece, black hair, elegant, mystery, mature", "style": "sepia_backlit", "name": "robin_sepia"},
    {"prompt": "1girl, ai hoshino, oshi no ko, long hair, star eyes, idol, sparkling", "style": "genshin", "name": "ai_genshin"},
    {"prompt": "1girl, ruby hoshino, oshi no ko, blonde hair, star eyes, idol, energetic", "style": "inuyasha", "name": "ruby_inuyasha"},
]

TOTAL = len(JOBS)
